export const NEW = "NEW";
export const APPROVED = "APPROVED";
export const CLIENT_APPROVED = "CLIENT_APPROVED";

export const ASSIGNED = "ASSIGNED"; 
export const ARRIVAL_TO_PICKUP = "ARRIVAL_TO_PICKUP"
export const OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY";
export const ARRIVE_AT_DESTINATION = "ARRIVE_AT_DESTINATION";
export const DELIVERED = "DELIVERED";

export const REJECTED = "REJECTED";
export const CLIENT_CANCELD = "CLIENT_CANCELED";

